server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: adverge-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/adplatform}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ad-platform-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

ad:
  bid:
    timeout: 5000
    cache-expiry: 300
  security:
    jwt:
      secret: ${JWT_SECRET:S3cre7K3y!F0rAdv3rg3}
      expiration: ${JWT_EXPIRATION:86400000}
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    exposed-headers: X-Timestamp,X-Signature

logging:
  level:
    root: INFO
    com.adverge: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.data.redis: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO 